### ISSUE TITLE
Make new Canonical URIs to match BFE

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/ssb-uri-spec#5]
[SSB BFE](https://github.com/ssb-ngi-pointer/ssb-binary-field-encodings-spec) and SSB URIs happen to have similar formatting philosophy, i.e. 

- `<type byte> <format byte> <data bytes>` in binary
- `ssb:type/format/data`

So we should seek to unify these two. Ideally, all entries in BFE would have SSB URI counterparts, and vice-versa. But we can start by specifying only those that are immediately useful and used in software.

See also: 

- https://github.com/ssb-ngi-pointer/ssb-bfe/pull/23#discussion_r687475834
- `%OC0VZ2tSieejXQtM1i/vLkyHkDXVdPueI1FUrXZAAac=.sha256`

cc @mixmix @arj03

**Comment by staltz** [comment]
> My first reaction is that I don't agree :)

Right, if I think of experimental SSB URIs, that doesn't make sense in BFE.

**Comment by mixmix** [comment]
I mainly want to lock in message, feed, blob,
Others tbd

I'm also open to having aliases like msg===message

**Comment by staltz** [comment]
I think we have most/all URIs that we actually needed.
